`timescale 1ns / 1ps
//============================================================================
// Testbench for 2D CNN — CIFAR-10 Full-Precision + BatchNorm (Parallel, v4)
//
// Architecture (v4 — 4 conv layers):
//   Conv2D_1(3→32, 3×3, pad=1) → BN1 → ReLU → Pool2D(2×2) → 16×16×32
//   Conv2D_2(32→64, 3×3, pad=1) → BN2 → ReLU → Pool2D(2×2) → 8×8×64
//   Conv2D_3(64→64, 3×3, pad=1) → BN3 → ReLU (no pool)     → 8×8×64
//   Conv2D_4(64→64, 3×3, pad=1) → BN4 → ReLU (no pool)     → 8×8×64
//   GAP(8×8 → 1×1)                                           → 64
//   FC1(64→256) → BN5 → ReLU                                 → 256
//   FC2(256→10)                                               → 10
//
// Loads .mem files generated by cifar10_cnn_baseline.py, runs inference,
// reports result with per-layer cycle breakdown.
//============================================================================
module tb_cnn2d_cifar;

    // ---- Architecture parameters (must match cnn2d_top_cifar) ----
    parameter INPUT_H       = 32;
    parameter INPUT_W       = 32;
    parameter INPUT_CH      = 3;

    parameter CONV1_OUT_CH  = 32;
    parameter CONV1_KERNEL  = 3;
    parameter CONV1_PAD     = 1;
    parameter CONV1_OUT_H   = INPUT_H + 2*CONV1_PAD - CONV1_KERNEL + 1;  // 32
    parameter CONV1_OUT_W   = INPUT_W + 2*CONV1_PAD - CONV1_KERNEL + 1;  // 32

    parameter POOL1_SIZE    = 2;
    parameter POOL1_OUT_H   = CONV1_OUT_H / POOL1_SIZE;    // 16
    parameter POOL1_OUT_W   = CONV1_OUT_W / POOL1_SIZE;    // 16

    parameter CONV2_IN_CH   = CONV1_OUT_CH;                 // 32
    parameter CONV2_OUT_CH  = 64;
    parameter CONV2_KERNEL  = 3;
    parameter CONV2_PAD     = 1;
    parameter CONV2_OUT_H   = POOL1_OUT_H + 2*CONV2_PAD - CONV2_KERNEL + 1;  // 16
    parameter CONV2_OUT_W   = POOL1_OUT_W + 2*CONV2_PAD - CONV2_KERNEL + 1;  // 16

    parameter POOL2_SIZE    = 2;
    parameter POOL2_OUT_H   = CONV2_OUT_H / POOL2_SIZE;    // 8
    parameter POOL2_OUT_W   = CONV2_OUT_W / POOL2_SIZE;    // 8

    parameter CONV3_IN_CH   = CONV2_OUT_CH;                 // 64
    parameter CONV3_OUT_CH  = 64;
    parameter CONV3_KERNEL  = 3;
    parameter CONV3_PAD     = 1;
    parameter CONV3_OUT_H   = POOL2_OUT_H + 2*CONV3_PAD - CONV3_KERNEL + 1;  // 8
    parameter CONV3_OUT_W   = POOL2_OUT_W + 2*CONV3_PAD - CONV3_KERNEL + 1;  // 8

    parameter CONV4_IN_CH   = CONV3_OUT_CH;                 // 64
    parameter CONV4_OUT_CH  = 64;
    parameter CONV4_KERNEL  = 3;
    parameter CONV4_PAD     = 1;
    parameter CONV4_OUT_H   = CONV3_OUT_H + 2*CONV4_PAD - CONV4_KERNEL + 1;  // 8
    parameter CONV4_OUT_W   = CONV3_OUT_W + 2*CONV4_PAD - CONV4_KERNEL + 1;  // 8

    parameter GAP_OUT       = CONV4_OUT_CH;                 // 64
    parameter FC1_IN        = GAP_OUT;                      // 64
    parameter FC1_OUT       = 256;
    parameter FC2_OUT       = 10;
    parameter PAD           = 20;

    parameter PARALLEL_CH   = 16;

    parameter FC1_WIDTH     = PAD + FC1_IN + PAD - 1;       // 103
    parameter FC2_WIDTH     = PAD + FC1_OUT + PAD - 1;      // 295

    parameter BITS          = 31;
    localparam OUTPUT_BITS  = BITS + 8 + 8;  // Two FC layers add 8 bits each

    // Timing
    parameter CLK_PERIOD_NS   = 10;
    parameter SIM_DURATION_NS = 20_000_000;  // 20 ms — generous for 4 conv layers

    // ---- Weight array sizes ----
    localparam CONV1_W_SIZE = CONV1_OUT_CH * INPUT_CH    * CONV1_KERNEL * CONV1_KERNEL;  // 864
    localparam CONV2_W_SIZE = CONV2_OUT_CH * CONV2_IN_CH * CONV2_KERNEL * CONV2_KERNEL;  // 18,432
    localparam CONV3_W_SIZE = CONV3_OUT_CH * CONV3_IN_CH * CONV3_KERNEL * CONV3_KERNEL;  // 36,864
    localparam CONV4_W_SIZE = CONV4_OUT_CH * CONV4_IN_CH * CONV4_KERNEL * CONV4_KERNEL;  // 36,864

    // ---- DUT signals ----
    reg  clk;
    reg  rstn;

    // Input image — 32×32×3 = 3072 Q16.16 values (channel-first)
    reg signed [31:0] data_in [0 : INPUT_H * INPUT_W * INPUT_CH - 1];

    // Conv2D weights & biases
    reg signed [31:0] conv1_w [0 : CONV1_W_SIZE - 1];
    reg signed [31:0] conv1_b [0 : CONV1_OUT_CH - 1];
    reg signed [31:0] conv2_w [0 : CONV2_W_SIZE - 1];
    reg signed [31:0] conv2_b [0 : CONV2_OUT_CH - 1];
    reg signed [31:0] conv3_w [0 : CONV3_W_SIZE - 1];
    reg signed [31:0] conv3_b [0 : CONV3_OUT_CH - 1];
    reg signed [31:0] conv4_w [0 : CONV4_W_SIZE - 1];
    reg signed [31:0] conv4_b [0 : CONV4_OUT_CH - 1];

    // BatchNorm parameters (Q16.16 per channel)
    reg signed [31:0] conv1_bn_scale [0 : CONV1_OUT_CH - 1];
    reg signed [31:0] conv1_bn_shift [0 : CONV1_OUT_CH - 1];
    reg signed [31:0] conv2_bn_scale [0 : CONV2_OUT_CH - 1];
    reg signed [31:0] conv2_bn_shift [0 : CONV2_OUT_CH - 1];
    reg signed [31:0] conv3_bn_scale [0 : CONV3_OUT_CH - 1];
    reg signed [31:0] conv3_bn_shift [0 : CONV3_OUT_CH - 1];
    reg signed [31:0] conv4_bn_scale [0 : CONV4_OUT_CH - 1];
    reg signed [31:0] conv4_bn_shift [0 : CONV4_OUT_CH - 1];

    // FC biases (weights loaded internally by layer_seq_cifar)
    reg signed [31:0] fc1_b [0 : FC1_OUT - 1];
    reg signed [31:0] fc2_b [0 : FC2_OUT - 1];

    // FC1 BatchNorm parameters (BN5)
    reg signed [31:0] fc1_bn_scale [0 : FC1_OUT - 1];
    reg signed [31:0] fc1_bn_shift [0 : FC1_OUT - 1];

    // Output
    wire signed [BITS+16:0] cnn_out [0 : FC2_OUT - 1];

    // ---- DUT instantiation ----
    cnn2d_top_cifar #(
        .INPUT_H      (INPUT_H),
        .INPUT_W      (INPUT_W),
        .INPUT_CH     (INPUT_CH),
        .CONV1_OUT_CH (CONV1_OUT_CH),
        .CONV1_KERNEL (CONV1_KERNEL),
        .CONV1_PAD    (CONV1_PAD),
        .CONV2_IN_CH  (CONV2_IN_CH),
        .CONV2_OUT_CH (CONV2_OUT_CH),
        .CONV2_KERNEL (CONV2_KERNEL),
        .CONV2_PAD    (CONV2_PAD),
        .CONV3_IN_CH  (CONV3_IN_CH),
        .CONV3_OUT_CH (CONV3_OUT_CH),
        .CONV3_KERNEL (CONV3_KERNEL),
        .CONV3_PAD    (CONV3_PAD),
        .CONV4_IN_CH  (CONV4_IN_CH),
        .CONV4_OUT_CH (CONV4_OUT_CH),
        .CONV4_KERNEL (CONV4_KERNEL),
        .CONV4_PAD    (CONV4_PAD),
        .FC1_OUT      (FC1_OUT),
        .FC2_OUT      (FC2_OUT),
        .PAD          (PAD),
        .PARALLEL_CH  (PARALLEL_CH),
        .BITS         (BITS),
        .FC1_WEIGHT_FILE("fc1_w.mem"),
        .FC2_WEIGHT_FILE("fc2_w.mem")
    ) dut (
        .clk             (clk),
        .rstn            (rstn),
        .data_in         (data_in),
        .conv1_w         (conv1_w),
        .conv1_b         (conv1_b),
        .conv2_w         (conv2_w),
        .conv2_b         (conv2_b),
        .conv3_w         (conv3_w),
        .conv3_b         (conv3_b),
        .conv4_w         (conv4_w),
        .conv4_b         (conv4_b),
        .conv1_bn_scale  (conv1_bn_scale),
        .conv1_bn_shift  (conv1_bn_shift),
        .conv2_bn_scale  (conv2_bn_scale),
        .conv2_bn_shift  (conv2_bn_shift),
        .conv3_bn_scale  (conv3_bn_scale),
        .conv3_bn_shift  (conv3_bn_shift),
        .conv4_bn_scale  (conv4_bn_scale),
        .conv4_bn_shift  (conv4_bn_shift),
        .fc1_b           (fc1_b),
        .fc2_b           (fc2_b),
        .fc1_bn_scale    (fc1_bn_scale),
        .fc1_bn_shift    (fc1_bn_shift),
        .cnn_out         (cnn_out)
    );

    // ---- Clock ----
    initial clk = 1'b0;
    always #(CLK_PERIOD_NS / 2) clk = ~clk;

    // ---- Cycle counter ----
    integer cycle_count;
    always @(posedge clk or negedge rstn) begin
        if (!rstn)
            cycle_count <= 0;
        else
            cycle_count <= cycle_count + 1;
    end

    // ---- Per-layer cycle capture ----
    integer reset_cycle;
    integer conv1_pool1_cycle;
    integer conv2_pool2_cycle;
    integer conv3_cycle;
    integer conv4_cycle;
    integer gap_cycle;
    integer fc1_cycle;
    integer fc2_cycle;

    // ---- One-shot flags ----
    reg fc1_done_seen;
    reg fc2_done_seen;
    initial begin fc1_done_seen = 0; fc2_done_seen = 0; end

    // ---- Argmax vars ----
    integer detected_class;
    integer n;
    reg signed [BITS+16:0] max_val;

    // CIFAR-10 class names
    // 0=airplane 1=automobile 2=bird 3=cat 4=deer
    // 5=dog 6=frog 7=horse 8=ship 9=truck

    // Expected label
    reg [31:0] expected_label_arr [0:0];
    integer    expected_label;

    // ---- Argmax task ----
    task find_predicted_class;
        begin
            max_val = cnn_out[0];
            detected_class = 0;
            for (n = 1; n < FC2_OUT; n = n + 1) begin
                if (cnn_out[n] > max_val) begin
                    max_val = cnn_out[n];
                    detected_class = n;
                end
            end
        end
    endtask

    // ---- Display task ----
    task display_all_outputs;
        begin
            $display("============================================================");
            $display("  CIFAR-10 CNN + BN OUTPUT VALUES  (Q16.16 raw logits)");
            $display("============================================================");
            for (n = 0; n < FC2_OUT; n = n + 1) begin
                $display("  Output[%0d] (class %0d) = %0d", n, n, cnn_out[n]);
            end
            $display("============================================================");
        end
    endtask

    // ---- Main stimulus ----
    initial begin
        $display("\n============================================================");
        $display("  CIFAR-10 CNN + BATCHNORM TESTBENCH - LOADING DATA (v4)");
        $display("  Architecture: Conv1(3->32) + Conv2(32->64) + Conv3(64->64)");
        $display("                + Conv4(64->64) + GAP + FC1(64->256) + FC2(256->10)");
        $display("  Parallelism:  %0d filters per group", PARALLEL_CH);
        $display("============================================================\n");

        // ---- Load conv2d weights ----
        $display("[INFO] Loading Conv1 weights (conv1_w.mem) -- %0d entries ...",
                 CONV1_W_SIZE);
        $readmemh("conv1_w.mem", conv1_w);

        $display("[INFO] Loading Conv1 biases (conv1_b.mem) -- %0d entries ...",
                 CONV1_OUT_CH);
        $readmemh("conv1_b.mem", conv1_b);

        $display("[INFO] Loading Conv2 weights (conv2_w.mem) -- %0d entries ...",
                 CONV2_W_SIZE);
        $readmemh("conv2_w.mem", conv2_w);

        $display("[INFO] Loading Conv2 biases (conv2_b.mem) -- %0d entries ...",
                 CONV2_OUT_CH);
        $readmemh("conv2_b.mem", conv2_b);

        $display("[INFO] Loading Conv3 weights (conv3_w.mem) -- %0d entries ...",
                 CONV3_W_SIZE);
        $readmemh("conv3_w.mem", conv3_w);

        $display("[INFO] Loading Conv3 biases (conv3_b.mem) -- %0d entries ...",
                 CONV3_OUT_CH);
        $readmemh("conv3_b.mem", conv3_b);

        $display("[INFO] Loading Conv4 weights (conv4_w.mem) -- %0d entries ...",
                 CONV4_W_SIZE);
        $readmemh("conv4_w.mem", conv4_w);

        $display("[INFO] Loading Conv4 biases (conv4_b.mem) -- %0d entries ...",
                 CONV4_OUT_CH);
        $readmemh("conv4_b.mem", conv4_b);

        // ---- Load BatchNorm parameters ----
        $display("[INFO] Loading Conv1 BN scale/shift -- %0d channels ...",
                 CONV1_OUT_CH);
        $readmemh("conv1_bn_scale.mem", conv1_bn_scale);
        $readmemh("conv1_bn_shift.mem", conv1_bn_shift);

        $display("[INFO] Loading Conv2 BN scale/shift -- %0d channels ...",
                 CONV2_OUT_CH);
        $readmemh("conv2_bn_scale.mem", conv2_bn_scale);
        $readmemh("conv2_bn_shift.mem", conv2_bn_shift);

        $display("[INFO] Loading Conv3 BN scale/shift -- %0d channels ...",
                 CONV3_OUT_CH);
        $readmemh("conv3_bn_scale.mem", conv3_bn_scale);
        $readmemh("conv3_bn_shift.mem", conv3_bn_shift);

        $display("[INFO] Loading Conv4 BN scale/shift -- %0d channels ...",
                 CONV4_OUT_CH);
        $readmemh("conv4_bn_scale.mem", conv4_bn_scale);
        $readmemh("conv4_bn_shift.mem", conv4_bn_shift);

        // ---- Load FC biases + BN ----
        $display("[INFO] Loading FC1 biases (fc1_b.mem) -- %0d biases ...", FC1_OUT);
        $readmemh("fc1_b.mem", fc1_b);

        $display("[INFO] Loading FC1 BN scale/shift -- %0d neurons ...", FC1_OUT);
        $readmemh("fc1_bn_scale.mem", fc1_bn_scale);
        $readmemh("fc1_bn_shift.mem", fc1_bn_shift);

        $display("[INFO] Loading FC2 biases (fc2_b.mem) -- %0d biases ...", FC2_OUT);
        $readmemh("fc2_b.mem", fc2_b);

        // ---- Load input & label ----
        $display("[INFO] Loading input data (data_in.mem) -- %0d pixels (3x32x32) ...",
                 INPUT_H * INPUT_W * INPUT_CH);
        $readmemh("data_in.mem", data_in);

        $display("[INFO] Loading expected label (expected_label.mem) ...");
        $readmemh("expected_label.mem", expected_label_arr);
        expected_label = expected_label_arr[0];
        $display("[INFO] Expected label: %0d\n", expected_label);

        // ---- Reset ----
        rstn = 1'b0;
        #(CLK_PERIOD_NS * 2);
        rstn = 1'b1;
        reset_cycle = cycle_count;
        $display("[INFO] Reset released at %0t ns (cycle %0d). Inference running ...\n",
                 $time, reset_cycle);

        // ---- Wait for inference ----
        #(SIM_DURATION_NS);

        // ---- Results ----
        $display("\n");
        $display("############################################################");
        $display("#  CIFAR-10 CNN + BN INFERENCE COMPLETE - RESULTS (v4)     #");
        $display("############################################################\n");

        display_all_outputs;
        find_predicted_class;

        $display("");
        $display("  >>> DETECTED CLASS: %0d <<<", detected_class);
        $display("  >>> Confidence (raw Q16.16 logit): %0d <<<", max_val);
        $display("");
        $display("  --- EXPECTED CLASS: %0d ---", expected_label);
        $display("");
        if (detected_class == expected_label)
            $display("  *** RESULT: PASS ***");
        else
            $display("  *** RESULT: FAIL -- Expected %0d but got %0d ***",
                     expected_label, detected_class);
        $display("");

        // ---- Cycle breakdown ----
        $display("============================================================");
        $display("  CYCLE BREAKDOWN");
        $display("============================================================");
        $display("  Conv1+BN1+Pool1  done at cycle: %0d", conv1_pool1_cycle);
        $display("  Conv2+BN2+Pool2  done at cycle: %0d", conv2_pool2_cycle);
        $display("  Conv3+BN3        done at cycle: %0d", conv3_cycle);
        $display("  Conv4+BN4        done at cycle: %0d", conv4_cycle);
        $display("  GAP              done at cycle: %0d", gap_cycle);
        $display("  FC1+BN5          done at cycle: %0d", fc1_cycle);
        $display("  FC2              done at cycle: %0d", fc2_cycle);
        $display("  TOTAL inference cycles: %0d", fc2_cycle - reset_cycle);
        $display("============================================================\n");

        #(CLK_PERIOD_NS * 2);
        $finish;
    end

    // ---- Monitor layer done signals ----
    always @(posedge dut.pool1_done) begin
        conv1_pool1_cycle = cycle_count;
        $display("[INFO] Conv1+BN1+Pool1 DONE at %0t ns (cycle %0d).",
                 $time, conv1_pool1_cycle);
    end
    always @(posedge dut.pool2_done) begin
        conv2_pool2_cycle = cycle_count;
        $display("[INFO] Conv2+BN2+Pool2 DONE at %0t ns (cycle %0d).",
                 $time, conv2_pool2_cycle);
    end
    always @(posedge dut.conv3_done) begin
        conv3_cycle = cycle_count;
        $display("[INFO] Conv3+BN3 DONE at %0t ns (cycle %0d).",
                 $time, conv3_cycle);
    end
    always @(posedge dut.conv4_done) begin
        conv4_cycle = cycle_count;
        $display("[INFO] Conv4+BN4 DONE at %0t ns (cycle %0d).",
                 $time, conv4_cycle);
    end
    always @(posedge dut.gap_done) begin
        gap_cycle = cycle_count;
        $display("[INFO] GAP DONE at %0t ns (cycle %0d).", $time, gap_cycle);
    end
    always @(posedge dut.fc1_done) begin
        if (!fc1_done_seen) begin
            fc1_done_seen = 1;
            fc1_cycle = cycle_count;
            $display("[INFO] FC1+BN5 DONE at %0t ns (cycle %0d).",
                     $time, fc1_cycle);
        end
    end
    always @(posedge dut.u_fc2.counter_donestatus) begin
        if (!fc2_done_seen) begin
            fc2_done_seen = 1;
            fc2_cycle = cycle_count;
            $display("[INFO] FC2 DONE at %0t ns (cycle %0d).", $time, fc2_cycle);
        end
    end

endmodule
